#!/usr/bin/env bash

set -o errexit

current_folder=$(dirname "$0")
plug_list="${1:-$current_folder/plugins.txt}"
plug_folder="${2:-$HOME/.config/kak/autoload/remote}"
parallel="${3:-8}"

[[ ! -f "$plug_list" ]] && echo "USAGE: $0 [plugin-list] [plugin-folder] [parallel-workers]" && exit 1

mkdir -p "$plug_folder"

green='\033[0;32m'
blue='\033[0;34m'
nc='\033[0m'  # no color
export plug_folder green blue nc

retrieve_url() {
    url="$1"
    name=$(basename "$url")
    local="$plug_folder/$name"

    if [ -f "$local" ]
    then
        mv "$local" "$local".prev
    fi

    if wget --hsts-file= -q --timeout=15 "$url" -O "$local" 2>/dev/null
    then
        echo -e "Updated ${blue}${name}${nc}!"
        if [ -f "$local".prev ]
        then
            # echo -e "${green}# ${name}:${nc}"
            git diff --no-index --stat -- "$local".prev "$local"
            rm -f "$local".prev
        fi
    else
        echo -e "Could not retrieve ${green}$url${nc}, preserving old version if exists..."
        mv "$local".prev "$local" 2>/dev/null
    fi
}
export -f retrieve_url

# retrieve URLs in parallel
grep -v '^\s*#' "$plug_list" | xargs -I {} -d '\n' -P "$parallel" bash -c 'retrieve_url "{}"'
